# Generated by Django 5.0.1 on 2024-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(db_column='Subject', max_length=100)),
                ('Time', models.CharField(db_column='Time', max_length=100)),
                ('Body', models.CharField(db_column='Body', max_length=10000)),
                ('Email', models.CharField(db_column='Email', max_length=10000)),
            ],
            options={
                'db_table': 'Inbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Representatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reps', models.CharField(db_column='Reps', max_length=100)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
                ('Company', models.CharField(db_column='Company', max_length=100)),
            ],
            options={
                'db_table': 'Representatives',
                'managed': False,
            },
        ),
    ]
