# Generated by Django 5.0.1 on 2024-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_inbox_representatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(db_column='Email', max_length=1000)),
                ('Time', models.CharField(db_column='Time', max_length=100)),
                ('Body', models.CharField(db_column='Body', max_length=10000)),
                ('Subject', models.CharField(db_column='Subject', max_length=100)),
            ],
            options={
                'db_table': 'Inbox',
                'managed': False,
            },
        ),
    ]
